# Generated by Django 4.2 on 2023-04-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_adddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddate',
            name='timeofday',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening'), ('N', 'Night')], default='E', max_length=1),
        ),
    ]
